// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.5.3_pinia@2.3.1_typescript@5.9.3_vue@3.5.38_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/payload-plugin.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/head/runtime/plugins/unhead.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.5.3_pinia@2.3.1_typescript@5.9.3_vue@3.5.38_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/plugin.vue3.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/plugins/slideovers.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/plugins/modals.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/plugins/colors.js")> &
  InjectionType<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_161fdf9a01e2e5b5a6adf0fb2be02be2/node_modules/@nuxt/icon/dist/runtime/plugin.js")> &
  InjectionType<typeof import("../../plugins/sw.client")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:router' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload' | 'pinia' | 'nuxt:global-components' | 'nuxt:prefetch' | '@nuxt/icon'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
