export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptVercelAnalytics, useScriptPostHog, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptMixpanelAnalytics, useScriptBingUet, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptGoogleRecaptcha, useScriptGoogleSignIn, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptTikTokPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal, useScriptGravatar, useScriptAhrefsAnalytics, useScriptCalendly, useScriptLinkedInInsight, useScriptUsercentrics, useScriptSpeedCurve } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch } from '#app/composables/fetch';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta } from '../node_modules/.pnpm/nuxt@3.21.8_@parcel+watcher@2.5.6_@types+node@26.0.1_@vue+compiler-sfc@3.5.39_cac@6.7.1_d3518fc8f2132a5f64f5166ddf640cda/node_modules/nuxt/dist/pages/runtime/composables';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { useApi } from '../composables/useApi';
export { useAuth } from '../composables/useAuth';
export { useExamMonitor } from '../composables/useExamMonitor';
export { useOssUpload } from '../composables/useOssUpload';
export { usePdfCache } from '../composables/usePdfCache';
export { formatScore } from '../utils/format';
export { QUESTION_TYPE, QUESTION_TYPE_LABELS, QUESTION_TYPE_SHORT_LABELS, getTypeLabel, getTypeShortLabel, CHOICE_TYPES, isChoiceType } from '../utils/questionType';
export { defineShortcuts } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts';
export { useProvideButtonGroup, useInjectButtonGroup } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useButtonGroup';
export { useCarouselScroll } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useCarouselScroll';
export { useCopyToClipboard } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useCopyToClipboard';
export { useFormGroup } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useFormGroup';
export { modalInjectionKey, useModal } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useModal';
export { createPopper, usePopper } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/usePopper';
export { _useShortcuts, useShortcuts } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useShortcuts';
export { slidOverInjectionKey, useSlideover } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useSlideover';
export { useTimer } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useTimer';
export { useToast } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useToast';
export { useUI } from '../node_modules/.pnpm/@nuxt+ui@2.22.3_magicast@0.5.3_vite@7.3.5_@types+node@26.0.1_jiti@2.7.0_terser@5.48.0_y_85c30173c5606bdfe9911352c24dd0ef/node_modules/@nuxt/ui/dist/runtime/composables/useUI';
export { useAuthStore } from '../stores/auth';
export { useSettingsStore } from '../stores/settings';
export { useColorMode } from '../node_modules/@nuxtjs/color-mode/dist/runtime/composables';
export { defineStore, acceptHMRUpdate, usePinia, storeToRefs } from '../node_modules/.pnpm/@pinia+nuxt@0.9.0_magicast@0.5.3_pinia@2.3.1_typescript@5.9.3_vue@3.5.38_typescript@5.9.3__/node_modules/@pinia/nuxt/dist/runtime/composables';